### PR TITLE
Initial proposal for the code cleanup in deploy folder

### PR DESCRIPTION
**Pull request by kupermind**
My proposal would be to take all the repetitive and global calls outside of the scripts. Also, we could possibly create an array of addresses for the new deployed contracts before hand, and test them against those addresses when needed. Some other tests could be proposed based on the logic of the scripts.

### CODE REVIEW

**Comment by DavidMinarsch** [comment]
This makes sense!

I think it still has a small bug at the end:
Screenshot 2021-12-06 at 21 48 28

**Review by DavidMinarsch — CHANGES_REQUESTED** [review]
LGTM - some minor fixes needed

**Comment by DavidMinarsch** [comment]
Please also consider the latest changes I merged (https://github.com/valory-xyz/contracts-amm/pull/6)

**Comment by dvilelaf** [comment]
LGTM. Just the merge and small bug David mentioned.

**Comment by DavidMinarsch** [comment]
Screenshot 2021-12-07 at 15 47 22

Screenshot 2021-12-07 at 15 46 48
Compare both screenshots, main leads to liquidity in pools (cf reserves); not the case for this branch.

**Review by DavidMinarsch — APPROVED** [review]
LGTM

**Pull request merged**
